version: '3'

tasks:
  protoc:
    cmds:
      - protoc -I protos/proto ./protos/proto/*.proto --go_out=./protos/gen/go --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go --go-grpc_opt=paths=source_relative
